// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGqxKjPjIEKwM9097EBTwm_qc14-UImLA',
    appId: '1:977644416213:web:447ef8b75d47e238ae465c',
    messagingSenderId: '977644416213',
    projectId: 'fruit-hub-54f55',
    authDomain: 'fruit-hub-54f55.firebaseapp.com',
    storageBucket: 'fruit-hub-54f55.firebasestorage.app',
    measurementId: 'G-MEB276SVDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAG8Pc3WgzwmlKIMXk23zxMxE5V5wxFwM',
    appId: '1:977644416213:android:fa07d14746ed8c32ae465c',
    messagingSenderId: '977644416213',
    projectId: 'fruit-hub-54f55',
    storageBucket: 'fruit-hub-54f55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhuNLIDR05l2IzxxcgvIuqGhBwZl5CsjM',
    appId: '1:977644416213:ios:3418afce1642927aae465c',
    messagingSenderId: '977644416213',
    projectId: 'fruit-hub-54f55',
    storageBucket: 'fruit-hub-54f55.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhuNLIDR05l2IzxxcgvIuqGhBwZl5CsjM',
    appId: '1:977644416213:ios:3418afce1642927aae465c',
    messagingSenderId: '977644416213',
    projectId: 'fruit-hub-54f55',
    storageBucket: 'fruit-hub-54f55.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGqxKjPjIEKwM9097EBTwm_qc14-UImLA',
    appId: '1:977644416213:web:8d543c0f58dbf420ae465c',
    messagingSenderId: '977644416213',
    projectId: 'fruit-hub-54f55',
    authDomain: 'fruit-hub-54f55.firebaseapp.com',
    storageBucket: 'fruit-hub-54f55.firebasestorage.app',
    measurementId: 'G-ZE9776NP5W',
  );
}
